// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '__API_KEY_WEB__',
    appId: '__APP_ID_WEB__',
    messagingSenderId: '__MESSAGING_SENDER_ID__',
    projectId: '__PROJECT_ID__',
    authDomain: '__AUTH_DOMAIN__',
    storageBucket: '__STORAGE_BUCKET__',
    measurementId: '__MEASUREMENT_ID__',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtd-CynEKjANn2eKA_Qfzs-_ogZJKY0VU',
    appId: '1:621148800955:android:fe54bf4c0f1bd9d5eea69e',
    messagingSenderId: '621148800955',
    projectId: 'buslink-416e1',
    storageBucket: 'buslink-416e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3VZy12UZYnrDhcMlyFFFINy_aWTWPRM4',
    appId: '1:621148800955:ios:b2f2c81facbbaae3eea69e',
    messagingSenderId: '621148800955',
    projectId: 'buslink-416e1',
    storageBucket: 'buslink-416e1.firebasestorage.app',
    androidClientId:
        '621148800955-g07n1vbvvr3s50rqsme86ufh1rt8mij4.apps.googleusercontent.com',
    iosClientId:
        '621148800955-313pco6l33cvve7ll73rnphi4qf4skd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buslink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3VZy12UZYnrDhcMlyFFFINy_aWTWPRM4',
    appId: '1:621148800955:ios:b2f2c81facbbaae3eea69e',
    messagingSenderId: '621148800955',
    projectId: 'buslink-416e1',
    storageBucket: 'buslink-416e1.firebasestorage.app',
    androidClientId:
        '621148800955-g07n1vbvvr3s50rqsme86ufh1rt8mij4.apps.googleusercontent.com',
    iosClientId:
        '621148800955-313pco6l33cvve7ll73rnphi4qf4skd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buslink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlo0Mwe-N-NOLaMEDdxy_tj4TBS46_YhI',
    appId: '1:621148800955:web:906ac17744f69ffeeea69e',
    messagingSenderId: '621148800955',
    projectId: 'buslink-416e1',
    authDomain: 'buslink-416e1.firebaseapp.com',
    storageBucket: 'buslink-416e1.firebasestorage.app',
    measurementId: 'G-9BHY9T8KE4',
  );
}
